language: python
python:
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install coverage
  - pip install coveralls
  - pip install nose
  - pip install flake8
  - pip install flask
script:
  - nosetests tests --with-coverage --cover-package=viewer --cover-erase
  - flake8 --max-line-length=100 --ignore=E402,F403 viewer tests
after_success:
  - coveralls
